name: Release Build

on:
  release:
    types: [published]

jobs:
  build-and-zip:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Corepack enable
        run: corepack enable

      - name: Install GLib dev libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-bin libglib2.0-dev-bin

      - name: Run Makefile target
        run: make desk-changer@eric.gach.gmail.com.zip

      - name: Rename zip to include tag
        run: mv desk-changer@eric.gach.gmail.com.zip desk-changer@eric.gach.gmail.com-${{ github.event.release.tag_name }}.zip

      - name: Upload Release zip
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: "desk-changer@eric.gach.gmail.com-${{ github.event.release.tag_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
